### ISSUE TITLE
Add ` addCursorInteraction` method to the docs?

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb.js#1137]
Trying to help @michellechandra  confirm her [tutorial](http://docs.cartodb.com/tutorials/google_driving_directions/) steps... 

Found [` addCursorInteraction`](https://github.com/CartoDB/cartodb.js/blob/3798323b953318576fac7ef00dede0aeec81e978/src/vis/vis.js#L1502) and also the [`remove cursor interaction`](https://github.com/CartoDB/cartodb.js/blob/3798323b953318576fac7ef00dede0aeec81e978/src/vis/vis.js#L1513) method.  Doesn't `featureClick` do the same thing? 
- Why would you use one method over the other?
- Should `add & remove CursorInteraction` be added to the API docs?

@alonsogarciapablo , please advise.

**Comment by alonsogarciapablo** [comment]
I'm not familiar with `addCursorInteraction` and `removeCursorInteraction` at all so I'm not sure if they are actually needed in the tutorial. I'd try to run the example in the tutorial without the usage of `addCursorInteraction` and see if everything still works fine (cursor changes when hovering over a feature).... Otherwise, we'll have to ask @javisantana, which probably knows about the story behind these two methods....

**Comment by michellechandra** [comment]
Testing with my tutorial code and finding that the mouse pointer changes to a finger point with the addCursorInteraction method (missing if I remove and just have the featureClick event.) Prob worth documenting!

**Comment by csobier** [comment]
As per @javisantana, this is an internal object that the user shouldn't know about. Closing as "wontfix" and deleting the related PR.  Michelle will update her tutorial accordingly.
