### ISSUE TITLE
Infinite loop on Map instantiation success => Analysis poller.start()

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#1283]
Found this while investigating https://github.com/CartoDB/cartodb/issues/7523 but have not managed to pinpoint exactly _why_.

The calls from the editor looks legit and are done, but then cartodb.js enters an infinite loop of requests between checking status of a node and doing an map-instantiation:

- [windshaft/map-base `instanceCreated` event](https://github.com/CartoDB/cartodb.js/blob/v4/src/windshaft/map-base.js#L77) - [`visView_onMapInstanceCreated`](https://github.com/CartoDB/cartodb.js/blob/v4/src/vis/vis-view.js#L266)
- [`analysisPoller.start()`](https://github.com/CartoDB/cartodb.js/blob/v4/src/analysis/analysis-poller.js#L19)
- start over…

Seems like the point-in-polygon node is in `pending` state during this time, if that helps.

**Comment by viddo** [comment]
Could this be related to recent changes of [#1276 Mark analysis node that changed as "failed" if request to Maps API fails](https://github.com/CartoDB/cartodb.js/pull/1276)?

**Comment by alonsogarciapablo** [comment]
Yes, so the problem is that 

1. Map instance is created.
2. One of the analysis nodes (point in polygon) is "pending" so polling starts.
3. When node becomes "ready" a new map instance is created.
4. One of the analysis nodes (point in polygon) is "pending" **again** so polling starts **again**
5. rinse, repeat ...

In theory, the Maps API should somehow know that the analysis has been completed before and should return the "ready" status as long as we send the same payload.

Talked to @rochoa about it and it seems something that needs to be fixed at the Maps API level, so I'll open an issue there.

**Comment by viddo** [comment]
Although, shouldn't cartodb.js be resilient to this kind of malfunctions? E.g. in this case, if it's already polling why start the poll again?

**Comment by alonsogarciapablo** [comment]
CartoDB.js keeps polling as long as the node is "pending". When the node becomes "ready" polling stops and a new instance of the map is created. At that point, from the POV of CartoDB.js, we're "starting from scratch again", so it'd be hard to tell wether a change from "ready" to "pending" state in a node should trigger a map reload or not.

I guess one way to stop this particular infinite loop would be to check if the status of analysis node that was "ready" has changed, and the payload that was used to create the map is the same as the payload that will be used again...

**Comment by viddo** [comment]
Just asking in case we could detect/prevent it from happening again, this kind of bug could easily lead to an overload of our own APIs.

**Comment by alonsogarciapablo** [comment]
I'll reopen it an try to fix it some time in the future.
