### ISSUE TITLE
Loader bar z-index is wrong

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb.js#1311]
![screen shot 2016-06-21 at 13 54 02](https://cloud.githubusercontent.com/assets/132149/16228498/b5955678-37b7-11e6-93f6-e3f6b9937e45.png)

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
