### ISSUE TITLE
Widgets using output of an analysis doesn't get refreshed when filtering in another widget

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#1345]
@saleiva commented on [Fri Jul 08 2016](https://github.com/CartoDB/cartodb/issues/8710)

But they get refreshed after panning the map.
Test in the map above in the formula widget
https://team.carto.com/u/ernestomb/builder/a89de72e-3fa4-11e6-80c4-0e674067d321/embed?state=%7B%22map%22%3A%7B%22center%22%3A%5B40.419769381446194%2C-3.6927795410156246%5D%2C%22zoom%22%3A12%7D%2C%22widgets%22%3A%7B%22c7ea4ffc-82b0-4cc7-8e4e-abc9fa9ab63f%22%3A%7B%22acceptedCategories%22%3A%5B%22L5%22%5D%7D%7D%7D

---

@viddo commented on [Mon Jul 11 2016](https://github.com/CartoDB/cartodb/issues/8710#issuecomment-231670624)

Moving and reassigning, since this should be handled internally in cartodb.js, by updating the dataviews appropriately.

**Comment by alonsogarciapablo** [comment]
I'm looking into this... Some findings so far:

1. the formula widget (Total Population around) is linked to an analysis with id "b2":

```
{
  "id": "b2",
  "type": "data-observatory-measure",
  "params": {
    "source": {
      "id": "b1",
      "type": "buffer",
      "params": {
        "source": {
          "id": "a0",
          "type": "source",
          "params": {
            "query": "SELECT * FROM madrid_metro_stations"
          }
        },
        "radius": 1000
      }
    },
    "final_column": "pop",
    "segment_name": "es.ine.t1_1",
    "percent": false
  }
}
```

2. the other two widgets (Metro Line and Metro Station) are linked to "a0":

```
{
  "id": "a0",
  "type": "source",
  "params": {
    "query": "SELECT * FROM madrid_metro_stations"
  }
}
```

Until now, widgets/dataviews were only refreshed if [this was true](https://github.com/CartoDB/cartodb.js/blob/v4/src/dataviews/dataview-model-base.js#L169-L170). In this case, the formula widget is linked to a different layer than the other two widgets, and that's why widgets are not "connected".

We should change things to:

1. Work with source IDs instead of layer IDs.
2. Take into account that sources are now related... eg: "b2" depends on "a0", so filtering "a0" affect widgets that depend on "b2".

**Comment by alonsogarciapablo** [comment]
Fixed in https://github.com/CartoDB/cartodb.js/pull/1360.
