### ISSUE TITLE
list of visualizations with problems with tangram

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#1572]
nº | vis | errors | fixed
------------ | ------------ | ------------- | -------------
1 | [link](https://team.carto.com/u/saleiva/builder/12223888-bc9d-4475-b6a2-34df0729523b/embed?vector=true) | no errors in console, does not show anything | true
2 | [link](https://team.carto.com/u/saleiva/builder/8123f4ff-52eb-4b9e-81dc-5ecf69469f9f/embed?vector=true) | the colors and the layer order aren't the same | true
3 |[link](https://team.carto.com/u/saleiva/builder/56e56fb2-8615-11e6-bcaf-0e05a8b3e3d7/embed?vector=true) | the opacity 0 is applied as 1 | true
4 |[link](https://team.carto.com/u/javi/builder/7a4e26b8-435f-11e6-91cb-0e674067d321/embed) | does not show anything | false
5 |[link](https://team.carto.com/u/rochoa/builder/4e406e8a-fda6-11e6-a665-0e3ff518bd15/embed?vector=true) | line glitch in polygon at zoom=6 | false

**Comment by alonsogarciapablo** [comment]
@javisantana it works for me:

<img width="893" alt="screen shot 2017-02-08 at 16 57 36" src="https://cloud.githubusercontent.com/assets/390398/22745121/c2175f12-ee1f-11e6-9951-5973b54f4ae0.png">

**Comment by donflopez** [comment]
The four is working on tangram-carto directly, it seems to be related with the mvt endpoint, have you publish it @javisantana?

**Comment by dv343** [comment]
I've checked all of them after the last update in production.

The first one works fine.
The other four fallback to raster because the CartoCSS has multiple symbolizers on the same layer. That is unsupported by Tangram, but we correctly detect the case to do the fallback.
It would work (not exactly the same, but very similar) if the CartoCSS had multiple layers, one for each symbolizer. The draw order would have changed, but Tangram could render it.
