### ISSUE TITLE
[CARTO Milestone] Migrate build system to webpack

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb.js#1637]
To have a homogeneous behaviour in all our libraries ecosystem, we have to migrate the actual grunt-browserify bundle system to a more actual approach based on webpack and npm scripts, fully compatible with modern technologies, more performant and useful.

**Comment by ivanmalagon** [comment]
:+1: to that.

In Builder we're already moving to Webpack. We should be aligned. Moreover, in order to get `cartodb.js` in Webpack with no problems we have to use plugins and shim loaders. Mainly because of libraries on `vendor` folder.

It'd be great to have `cartodb.js` webpacked so we could user your configuration and not depend on these shims.
