### ISSUE TITLE
[CARTO Milestone] Study changing underscore.js

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb.js#1650]
We are using underscore as our main utility library, this version is from Apr 2015 and it doesn't have tonnes of improvements that Lodash has (performance, lazy evaluation, etc...), also I suggest using lodash-fp wich can improve a lot our daily development work.

**Comment by nobuti** [comment]
The same concern as jquery, not sure if they are 100% compatible, at least from the backbone point of view. But to be fair, webpack requires lodash as a dependency, it should be nice to get rid of underscore.

**Comment by ivanmalagon** [comment]
I was about to say the same thing. Being a backbone dependency will make it hard to change.

When moving the tests from Browserify to Lodash I ran into a problem related to templates. It was supossed to behave the same way but the truth it's that I had to clone a TPL loader repo to use `underscore` instead of `lodash`. 

I'm also with changing this being a good thing but we'll need to keep an eye on it.
