### ISSUE TITLE
Tap on iOS10 mobile embed jumps to page bottom

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1652]
@noguerol commented on [Wed May 10 2017](https://github.com/CartoDB/cartodb/issues/12105)

### Context
One tap over an embed on mobile iOS10 jumps the browser (Safari) until the page bottom. If you scroll back to the embed, the normal double tap zoom interaction works as expected. This is not happening with Editor embeds. 

Comes from: https://github.com/CartoDB/support/issues/660

### Steps to Reproduce

1. Open[ this](http://www.michellechandra.com/lorem/) on iOS10 Safari.
2. Tap on the second embed, generated with Builder

### Current Result
Browser jumps to the bottom

### Expected result
Normal zoom double tap

---

@xavijam commented on [Fri May 12 2017](https://github.com/CartoDB/cartodb/issues/12105#issuecomment-301068171)

Moving to its right place.

**Comment by xavijam** [comment]
cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
This might be related: https://github.com/Leaflet/Leaflet/issues/5392 (thanks to @rjimenezda)

**Comment by rjimenezda** [comment]
I've debugged it a bit with the iOS Simulator and the jump happens right after the focus call:

https://github.com/Leaflet/Leaflet/blame/master/src/map/handler/Map.Keyboard.js#L85

The window.scrollTo is a red herring, since it's on embed it doesn't really matter.

I don't see any decent way of disabling that call without modifying native object prototypes, which is a big no-no, or patching Leaflet to disable that line before building, which is also kind of uncool.

**Comment by rjimenezda** [comment]
Maybe `HTMLElement.prototype.focus  = () => {}` isn't such a bad idea, but maybe doing it only for Safari.

**Comment by rjimenezda** [comment]
Same thing happens on Chrome for iOS (which makes sense, afaik iOS browsers are just fancy webviews)

**Comment by xavijam** [comment]
I've been checking the thing and it is true if we set the [`keyboard`](http://leafletjs.com/reference-1.0.3.html#map-keyboard) map attribute to false, the bug is not happening. Why not set that by default and then provide the possibility to enable/disable the keyboard map option?

**Comment by nobuti** [comment]
Deployed

**Comment by kevin-reilly** [comment]
Awesome guys.  Thanks for getting this done.
