### ISSUE TITLE
Make Mapzen API key configurable

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb.js#1669]
The search bar is not working at present. The issue seems related to 3rd party services, service limits and the like.

In order to get this fixed, certain controls must be applied on the credentials used, in order to avoid disclosure and abuse of API keys and incurring in extra charges.

The code is here: https://github.com/CartoDB/cartodb.js/blob/7ea6457edc3dcb5f37d6dfe047943443f02d5f28/src/geo/geocoder.js

and can also be found in statics downloaded by Builder.

One way to get around this could be to use the DS API as a proxy to geocoding services, but then an Engine API key needs to be provided.

Adding @kevin-reilly and @saleiva as this may affect Builder as a product. One example of this: what quota shall a public embed use for the search bar?

**Comment by saleiva** [comment]
There are a few options that popup in my mind
- Use a CARTO api KEY for this calls (not sure if it's feasible without doing hacks)
- Enable this only within builder, so if the user wants to enable this on embed and public maps, they need an Engine API key
- Enable this only if you have an Engine API key (within builder and in public maps).

**Comment by rafatower** [comment]
Well, I was referring to the typical SQL API key, sorry I called it Engine. And that cannot be disclosed on public maps

**Comment by rafatower** [comment]
cc/ @jorgesancha for awareness

**Comment by alonsogarciapablo** [comment]
@rafatower thanks for opening this issue! I could help with this if I knew how to proceed... 😿 

Question... does Mapzen allow to limit usage of an API key to a given domain / IP? (@jsanz)? That would allow us to generate keys that could only be used from our servers..

We'll need to change CartoDB.js a bit so that the API keys for Geocoders are customisable (eg: BUILDER should be able to tell CartoDB.js the Mapzen API key to use).

**Comment by alonsogarciapablo** [comment]
Also, can't we just create another account / key and use it in the meantime? We'll need a new account anyway? And... won't we need to pay if we reach the (free) limits anyway?

**Comment by jsanz** [comment]
From [their documentation](https://mapzen.com/documentation/overview/api-keys/#protect-your-api-keys):

> If you believe your API key has been compromised or used without your knowledge, contact Mapzen. You can also delete API keys or rotate them periodically in your app. There is not currently a default way to limit an API key for usage only on a particular web domain.

**Comment by jorgesancha** [comment]
cc @rochoa @javisantana 

Regarding Keys, we are creating the new API keys as we speak, but we need to decide several things here:

1) How does cartoDB.js know what key to use? Ideally somehow this should go through DataServices API so that, if in the future we decide to enable each user to have their keys, this would always return the correct key

2) In terms of usage, we can use quotas to control this, if I'm not mistaken? Can someone clarify if this is the case? If so, we need to review what quotas we want to set for each user

3) Whether we do this only for Builder and/or Embeds. @saleiva suggests two options, and I quote:
- Enable this only within builder, so if the user wants to enable this on embed and public maps, they need an Engine API key
- Enable this only if you have an Engine API key (within builder and in public maps).

Am I right on 1 and 2? Which one is it for 3?

**Comment by javisantana** [comment]
Just a note: we used to having 2 api keys for HERE:
- one for the geocoding (data services)
- another for client side geocoding and basemaps (so we could remove in case of someone abusing)

That's the best way, this problem does not have a good solution

**Comment by jorgesancha** [comment]
Ok, we are going to create two keys for production as Santana says for the time being.

**Comment by javisantana** [comment]
so the plan is:

- we add mapzen client keys in rails configuration. In case this is not set rails should not fail but the geocoder will not work
- those keys are sent to the embed/public_page and we configure carto.js using `cdb.config.set('client_mapzen_api_key', '<%=MAPZEN_CLIENT_KEYS %>')`
- we modify the geocoder.js so it uses `cdb.config.get('client_mapzen_api_key')'
- in case someone is developing apps with carto.js they should register in mapzen and set those configuration variables in carto.js

does it sound good?

**Comment by jorgesancha** [comment]
This (and having two different keys) solves the immediate problem. :+1: We then need to keep an eye on whether someone is abusing the embedded one and recycle the key or change strategy

**Comment by alonsogarciapablo** [comment]
I created https://github.com/CartoDB/cartodb/issues/12296 for the rails / backend side.

I'll work on the CartoDB.js side of things and do something along the lines of what @javisantana suggested. Thanks!

**Comment by alonsogarciapablo** [comment]
I changed the Mapzen API Key in https://github.com/CartoDB/cartodb.js/commit/dd3600de79743aa23d3bf86b1ac2821a3ce854b9 so that it works in the following days. I'm deploying it right now (cc: @jsanz).

I'll finish the more elegant solution next week.

**Comment by alonsogarciapablo** [comment]
I'm going to release a new version of CartoDB.js 3.x with the new Mapzen key. Unless someone has something to say I'll hardcode it for the time being. If we make it configurable in this version, we'll need to update the docs and Editor too, which doesn't make too much sense IMO now that we're close to migrating everyone to BUILDER.

Still planning to make it configurable for BUILDER though.
