### ISSUE TITLE
Stop throwing an error when a map can't be rendered with vector

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1706]
We are receiving tons of fake JS errors in our platform tracker due to this problem.
Basically, this map is throwing that error: 

https://team.carto.com/u/abel/builder/dd292541-e767-40f8-8bb5-78e359faf209/embed

For me, this is a priority because it is f****** our stats.

@noguerol @rubenmoya

**Comment by rubenmoya** [comment]
In production! 🚀

**Comment by alonsogarciapablo** [comment]
We're using this as a way to diagnose why some maps couldn't be rendered using vector (eg: when a TurboCarto property is not supported by Tangram)...  I can understand how this was probably adding a lot of noise in track.js and nobody was probably looking at theses error messages right now... Just commenting it here because this was a "feature" so we might need to rethink it.

cc: @rochoa, @jorgesancha, @javisantana and @IagoLast

**Comment by IagoLast** [comment]
Can we just use a `warn`? IMO a not supported feature is not an error.

**Comment by javisantana** [comment]
we were using errors to track support, ideally we would have a stats systems where we would push that kind of things. As we don't have such thing we used trackjs (not bad solution if trackjs would have a way to hide/filter those errors)

**Comment by xavijam** [comment]
TrackJS allows us:

- Hide the error.
- Group them into one.
- ... other choices :D.

**Comment by xavijam** [comment]
CARTO.js nothing, you can filter them in the web application.
