### ISSUE TITLE
Display default error tile when user reaches its limits

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1717]
When the user reaches its limits, it is likely errors will start coming from the Maps API. At that point, we need to display "error" tiles, and improve the user experience instead of leaving those ugly broken tiles.

## Caveats
- We have two map libraries, Leaflet and GMaps, both of them should support to display a default error tile.
- We should add the error tile image in the CARTO.js bundling (what about retina one? 😛 ).
- We have to decide with @CartoDB/engine team which is the proper 4XX error code returned by the API.

## Design
 
<img width="743" alt="screen shot 2017-08-11 at 11 21 18" src="https://user-images.githubusercontent.com/132146/29207622-3778fb2e-7e87-11e7-93ec-c6375e3d662a.png">

**Comment by rochoa** [comment]
> - We should add the error tile image in the CARTO.js bundling (what about retina one? 😛 ).

One of the discussions we had was about the possibility of using an _artificial_ layer to display the errors themselves. If that is still an option, do we want to use an image or we should aim for something more friendly to the user, like a fake HTML tile where you can link to different docs/resources explaining the problem.

> - We have to decide with @CartoDB/engine team which is the proper 4XX error code returned by the API.

Related to my previous point, we need to check if we want to return a [429 error](https://tools.ietf.org/html/rfc6585#section-4) and we can catch it at the client side, or we have to return an image with a `200 OK`.

**Comment by xavijam** [comment]
1. Well, I'd not add more logic or more layers when error appears. I'd bet for the simplest solution about the error image. Take into account we will display the "new overlay" warning the user about the problem.
2. True, @rubenmoya is on it, but I feel we will be ok with any of the error codes. 

Stay tuned.

**Comment by rubenmoya** [comment]
I've been doing some research about error tiles, both, Leaflet and GMaps have a `onerror` event, which basically is the [img onerror attribute](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/image#a-onerror), the status code shouldn't be a problem if the response is an invalid image.

**Comment by Jesus89** [comment]
Deployed in ded03 (also deployed Tiler `add-timeout-header` in ded03)

**Comment by xavijam** [comment]
:_)

**Comment by Jesus89** [comment]
Found unexpected behavior. Back to development :arrow_left:

**Comment by dgaubert** [comment]
Let me explain a little the following issue we have found while fetching **raster** tiles (`.png`):

Both, Leaflet and GMaps use `<img/>` tag to fetch tiles through `src` attribute. This tag fires just two events: `load` when everything goes right and `error` when the image received from server is not renderable. In other words, the status code of the response or headers are completely ignored. Thus, the server can send a `429` with a dummy tile and the browser will render the image and `load` will be fired. On the other hand, if server sends a `200` and the body of the response is, for instance, text or `null` the browser will display the __broken image icon__ and `error` event wil be fired.

So the problem here is that, we cannot know when a timeout error is received because `error` listeners will be fired in any case that the body of the response is not renderable (`null`, `text`, `json`). And the contrary, if the server sends a dummy tile the `load` listener will be fired in the same way it does with any tile.

We need to discuss on how to tackle this issue. cc/ @nobuti @rubenmoya @Jesus89

**Comment by dgaubert** [comment]
After a meeting there is a new approach on the table to know when a user is over the limits fetching `raster` tiles.

In backend, when a timeout limit has been reached by a user, we can store a temporal key in metadata (TTL ~30s) with the user, layergroupid, coords and the error and send a `429` response with a `null` body to fire the `onerror` listener in frontend. We can expose a new endpoint in order to provide the info related to the timeout error and the frontend can ask for the error type through the new endpoint. For instance:

Stored key:
`errors:{userid}:{layergroupid}:{z}:{x}:{y}`: `429`

Request to the new endpoint:
`/api/v1/map/errors/{user}/{layergroupid}/{z}/{x}/{y}`

Response:

```
{
   '429': true
}
```

Thoughts??

**Comment by rochoa** [comment]
I would NOT make errors stateful. Either we find a way to handle that at the client side, or we take another approach, but I would not store/expose errors that way.

**Comment by dgaubert** [comment]
I totally agree. I was aware of this but a I wanted to open a discussion in order to find a better solution.

If we discard the approach of store/expose errors, we have two options:

  - Find a way in *frontend* to handle different kind of errors with `<img/>` tag. It seems there is no way to handle those situation because the browser doesn't have a proper API to handle errors with `<img/>` tag.

  - In case of image error, show generic error pointing to a possible errors of limits. For example: displaying a dummy tile and a message: `Something went wrong. It might you are over the limits [blah blah ...]`

Have in mind this approach is only for `raster` in any other case we know when a timeout error happens.

**Comment by dgaubert** [comment]
# Acceptance steps (staging)

1. Go to [central](https://carto-staging.com/superadmin) and login as `full-admin`.
2. Search for an existent user or create a new one. 
3. Click `edit user`
4. Change the following properties:
  - `Timeout for user queries`: 500 (0.5 sec), 
  - `Timeout for public queries`: 500 (0.5 sec).
  - `Timeout for authenticated tile-rendering`: 0 (deactivated),
  - `Timeout for public tile-rendering`: 0 (deactivated)
5. Save changes (click `update user`)
6. Open a new browser's tab and login with user's credentials.
7. Create a new map with `populated_places_simple` dataset.
8. Edit `sql` for the layer:
  8.1 Go to `data` section of the layer.
  8.2 Open `expert-mode` and edit the sql as follows:
    - `SELECT *, pg_sleep(1) FROM ne_10m_populated_places_simple` =>`SELECT *, pg_sleep(1) FROM ne_10m_populated_places_simple`.
  8.3 Apply query.
9. Check tiles doesn't load and the timeout error is displayed.

HTH.

**Comment by piensaenpixel** [comment]
waiting for staging

**Comment by rubenmoya** [comment]
It's deployed to `ded15`, I gave @josecruz my account credentials

**Comment by piensaenpixel** [comment]
it doesn't work :( query is loading ....

![infinity](https://user-images.githubusercontent.com/1214201/30831363-71ea2268-a247-11e7-8058-d506c8d1db6d.jpg)


![image](https://user-images.githubusercontent.com/1214201/30831314-44538bdc-a247-11e7-82e9-9b14fdd6f511.png)

**Comment by rubenmoya** [comment]
The query is wrong, you have to replace the query, the one on the left of `=>` for the one on the left, you pasted everything. The query should be `SELECT *, pg_sleep(random()) FROM ne_10m_populated_places_simple`

**Comment by piensaenpixel** [comment]
hi :) 
Tile is working but I can't see the infobox

https://user-images.githubusercontent.com/14546701/27180748-2065338c-51d5-11e7-9218-81588afa15b3.png

![image](https://user-images.githubusercontent.com/1214201/30853552-68acc47c-a2af-11e7-8d75-0c00e8de274f.png)

**Comment by rubenmoya** [comment]
This PR is only for the tile overlay

**Comment by nobuti** [comment]
We need to implement the notification here. The general notification we have already implemented is only for the public view. This is because of the limitation in order to include the upselling part. So just to clarify:

- **For public embed** view, we will end up having this:
![image](https://user-images.githubusercontent.com/14546701/27280402-12fe9e0c-54e8-11e7-9c87-1211a7c44a69.png)
This is already implemented but for all views. We need to connect it with the error and limit its presence to the public view. I'll open the pertinent issue.
- **For builder** view, we will have the notification shown above.

So in order to implement the notification, @noguerol @piensaenpixel just a couple of questions:
- What does do the `Optimize your map`?
- Does link the upselling button to a generic page or should we segment by users type? I mean, whether the user is free, the page linked is different for the one shown for personal or enterprise accounts.
- That notification is expandable, we have not got that kind of notification so far. Not sure if we should implement it in the same way as the rest of notifications and open an issue in order to update the look and feel of all notifications.

**Comment by noguerol** [comment]
> What does do the Optimize your map?
We've removed that link from the new mockups.

> Does link the upselling button to a generic page or should we segment by users type? I mean, whether the user is free, the page linked is different for the one shown for personal or enterprise accounts.
It should go to the internal pricing page, regardless the user type. 

> That notification is expandable, we have not got that kind of notification so far. Not sure if we should implement it in the same way as the rest of notifications and open an issue in order to update the look and feel of all notifications.
We've removed collapsible notifications for now in the mockups. They will be implemented in the future.

**Comment by rubenmoya** [comment]
What's the internal pricing page @noguerol?

**Comment by xavijam** [comment]
Closing, it is in production, but not visible in fact ;).
