### ISSUE TITLE
Make internal classes public: Dataviews

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1731]
Users should be able to manage dataviews via the API.

Here's an example using a formula dataview.

```
var totalPopulation = new carto.dataview.Formula(countriesDataset, {
  column: 'population',
  params: {
    operation: carto.operation.SUM
  }
});
```

The following dataviews should be supported:
- [ ] Formula dataview
- [ ] Category dataview
- [ ] Histogram dataview
- [ ] TimeSeries dataview

**Comment by ivanmalagon** [comment]
I've added `TimeSeries` dataview.

Since we're wrapping the inner dataview, I think it's a good time to wrap `TimeSeries` to hide implementation details to the API consumer. In the end, it uses another histogram dataview but we have lots of duct tape to enable it to behave for two different usages. I think that we should hide this duct tape to the end user.

List dataview was already removed in previous PRs.

**Comment by Jesus89** [comment]
Split this ticket in 4 tickets
