### ISSUE TITLE
Expose metadata from CartoCSS/TurboCarto styles

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1733]
Developers should be able to get the metadata associated to the CartoCSS/TurboCarto that was given to the Maps API. Also, since CartoCSS/TurboCarto can be changed on runtime, developers should be able to detect when metadata of a given "style" has changed.

Here's some pseudocode:

```js
// We also want the legend to be refreshed when new metadata is available
citiesStyle.on('change:metadata', function (metadata) {
  console.log(metadata);
});
```

**Comment by Jesus89** [comment]
The 'metadataChanged' event is going to be added to the Layer object:

```js
layer.on('metadataChanged', function (metadata) {
  metadata.isBubble();
  metadata.isCategory();
  metadata.isChoropleth();
  console.log(metadata);
});
```

**Comment by makella** [comment]
@Jesus89 

One way to distinguish buckets and categories is by data type. Below are some ideas. 

Of course, the pairs don't have to go together in all cases, so there could be a way to mix and match.

### Value and Type
`var value = styleMetadata.getValue();`
`var type = styleMetadata.getType();`

### Quantity and Quality
`var quantity = styleMetadata.getQuantity();`
`var quality = styleMetadata.getQuality();`

### Value and Class
`var value = styleMetadata.getValue();`
`var class = styleMetadata.getClass();`
  - this could be confusing because the word `class` could also be used as a synonym for `bucket` 

### Measure and Type
`var measure = styleMetadata.getMeasure();`
`var type = styleMetadata.getType();`

### Scale and Group
`var scale = styleMetadata.getScale();`
`var group = styleMetadata.getGroup();`

### Range and Theme
`var range = styleMetadata.getRange();`
`var theme = styleMetadata.getTheme();`
- I know `range` in TurboCARTO scales a property and for creating a choropleth map we don't use `range` but it is distributing values over a range of colors.

**Comment by Jesus89** [comment]
Thanks @makella. We will use a getType() function to distinguish the type of the styleMetadata.
