### ISSUE TITLE
Events documentation

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb.js#2013]
While navigating the docs to explain something to Ruben related to events I felt a disturbance in the force.

Events are a crucial part of the development of CARTO.js apps but they're not a first class citizen on our docs.

What I missed:

- A reference to events in the left table of contents. At least a top entry called Events that points to the right place in the full reference.

![image](https://user-images.githubusercontent.com/1078228/35031707-59b520c8-fb64-11e7-908c-788545e7b3cc.png)

- Instead of `fires`, could we say `events`? Or at list a descriptive text saying something like 'This is the list of events that can be fired by whatever`

- A special section in the `quickstart guide`. Talking about how to set and unset event listeners in a general way. At least, marking that the event handling it's an important step in every CARTO.js app.

- Examples in each event in the full reference (this is an loooong task, we can tackle it bit by bit)

**Comment by csubira** [comment]
- 'Fires' replaced with 'Events' in reference page. Solved [here](https://github.com/CartoDB/documentation/pull/144).

- Regarding to 'Events' appearing in the sidebar menu or other related issues to make events a first level item in our hierarchy, I referenced this issue in [#1164](https://github.com/CartoDB/design/issues/1164) due to redesign of reference page and reference blocks in progress.

- Event section in Guides to be tackled in #2052
