### ISSUE TITLE
Layers disappear from Google Map after zooming in and then out

### ISSUE THREAD

**Issue by searoutefinder** [CartoDB/cartodb.js#2066]
A rather annoying issue that I have faced recently where on a google map instance you add you Carto layers using v4 of the API. Layers get displayed fine but after you zoom in and then out there is no way the contents would show.
I have checked the layer's visible states and a couple of other settings everything seems to be fine expect that the layers won't show any more.
The more you zoom in the more zoom layers become unable to display carto layer content.
Has anybody else faced this issue before? I checked and it is even present in the official examples.
Any help would be highly appreciated!

Thank you!

**Comment by ivanmalagon** [comment]
Hi Tamas.

What Google Maps version are you using? Recently, Google pushed a new version of Google Maps (v3.32) that introduces weird behaviours while using it with CARTO.js v4.

Please add the parameter `v=3.30` to the GMaps script tag.
```
<script type="text/javascript" src="http://www.maps.google.com/maps/api/js?v=3.30">
```

Our examples are not updated yet so that's the most likely issue.

Try that and let us know.

Thanks!

**Comment by searoutefinder** [comment]
Hello Ivan!

Actually I was using the latest version and changing the version back to 3.30 as you suggested did the trick and the map layers are now working as expected.
So thank you for your fast and answer and your help! Much appreciated!

Tamas

**Comment by ivanmalagon** [comment]
CARTO.js examples have been redeployed setting the Google Maps version to 3.30.

They're working now as expected.
