### ISSUE TITLE
Full screen button not working on Safari 8.0.3

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb.js#361]
I also tested in Version 8.0.2 (10600.2.5) over Mac OSX 10.10.1.

Notify: SB/4576792

**Comment by javierarce** [comment]
Does it throw a JavaScript error?

**Comment by Xatpy** [comment]
@javierarce No, it doesn't throw a Javascript error.

I've been researching, and it seems to be a **Bug with Safari**. 
References:
- [Stackoverflow I](http://stackoverflow.com/questions/8427413/webkitrequestfullscreen-fails-when-passing-element-allow-keyboard-input-in-safar) : *This is known Safari bug.* Sol-> **...(/Safari/.test(navigator.userAgent) ? undefined : Element.ALLOW_KEYBOARD_INPUT)**
- [Stackoverflow II](http://stackoverflow.com/questions/16150601/substitute-for-allow-keyboard-input-javascript-full-screen) : *Unfortunately, there isn't a good way to even do feature detection, since element.ALLOW_KEYBOARD_INPUT is defined in Safari, *
- [HTML5gamedevs](http://www.html5gamedevs.com/topic/2602-fullscreeninput-issue/) : *"For security reasons, most keyboard inputs have been blocked in the fullscreen mode. However, in Google Chrome you can request keyboard support by calling the method with a flag:
docElm.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
This does not work in Safari, and the method won’t be called.*
- [Hack.mozilla.org](https://hacks.mozilla.org/2012/01/using-the-fullscreen-api-in-web-browsers/)

I've done a patch and I'm "pull requesting" it.

**Comment by javierarce** [comment]
:ok_hand:

**Comment by Xatpy** [comment]
merged.
