### ISSUE TITLE
Legends are appearing for hidden layers

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb.js#609]
**Steps:**

* Create a map from two datasets
* Add a legend for each of them
* Hide one of the layers: the legend for that particular layer hides in the Editor
* Open the embed: the legend for the hidden layer is appearing

Editor:
![image](https://cloud.githubusercontent.com/assets/1730320/8773617/cdb12a02-2ed5-11e5-976f-c24984776f4d.png)

Embed:
![image](https://cloud.githubusercontent.com/assets/1730320/8773620/d4de32d4-2ed5-11e5-8a3d-e2cd47be0fca.png)

Example [here](https://vmg.cartodb.com/viz/b33e3b44-2ec4-11e5-9b27-0e853d047bba/embed_map)

**Comment by iriberri** [comment]
SB/5997339

**Comment by alonsogarciapablo** [comment]
Might be related to #488.

**Comment by alonsogarciapablo** [comment]
Hey, I was looking into this. There's a disconnection right now in the viz.json between the visibility of the layer and the visibility of the legends. Take the following excerpt from a viz.json for example:

```
{
  "layer_name": "barris_barcelona",
  "interactivity": "cartodb_id",
  "visible": false,
  "legend": {
    "type": "custom",
    "show_title": true,
    "title": "wadus2",
    "template": "",
    "visible": true,
    "items": [
      {
        "name": "Untitled",
        "visible": true,
        "value": "#cccccc",
        "sync": true
      }
    ]
  }
}
```

You can see how the layer has `"visible": false` but the legend has `"visible": true`. cartodb.js is taking that attribute into account to determine whether to show or hide legends. So perhaps a simple solution is to mark the legends as visible/hidden based on the visibility of the layer. What do you think @Kartones?

**Comment by Kartones** [comment]
Yep, no problem, I can override legend's visibility with layer's visibility when layer is `visible: false`. So you keep your customization: *"I want to show legends from layers A & C but not B, having all three visible and layer D hidden"*

Should be easy, I'll attack it on monday probably

**Comment by alonsogarciapablo** [comment]
Great. Thanks!

**Comment by Kartones** [comment]
Ok, after checking the code, I'm doing a backend check, but ideally this should be also fixed in the frontend, as backend just provided a container for "legend" and all inside is handled currently by the editor's JS. 

Anyway as I said providing a backend `legend.visibility && layer.visibility` check to be sure and making it work with existing viz.

**Comment by Kartones** [comment]
As explained at https://github.com/CartoDB/cartodb/issues/4696#issuecomment-125167615 my fix won't solve the issue as cartodb.js doesn't honours legend visibility but prioritizes each individual item's one, so even if I forcibly change legend visibility it still displays.

**Comment by alonsogarciapablo** [comment]
I'm re-taking this (another user reported it). It seems to be working for named maps but not in other cases, and it looks like `legend.visible` is not being taking into account in any case :(. It's currently not possible to hide legends using the UI. Legends are visible or hidden based on the visibility of the layer, so I'm going to update cartodb.js so that legends are only displayed if the layer is visible.
