### ISSUE TITLE
Error on createVis with no_cdn option

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb.js#645]
With ```3.15```, when loading a vizjson from an on-premise and using the ```no_cdn:true``` option the library returns an error. Same code with ```3.14``` works as expected.

![Conosle](http://i.imgur.com/vACXk2z.png)

More details at SB/6251218

**Comment by javisantana** [comment]
could you post some sample code?

**Comment by jsanz** [comment]
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <link rel="shortcut icon" href="http://cartodb.com/assets/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
          html, body, #map {
            height: 100%;
            padding: 0;
            margin: 0;
          }
        </style>
        <link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/3.15/themes/css/cartodb.css" />
        <script src="http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js"></script>
    </head>
    <body>
        <div id="map"></div>
        <script>
            $( document ).ready(function() {
              var viz = 'http://url-to-an-on-premise/viz.json';
              cartodb.createVis('map',viz,{no_cdn:true});
            });
        </script>
    </body>
</html>
```

Changing the version to ``3.14`` this code works.

**Comment by alonsogarciapablo** [comment]
The problem here is that the viz.json served by the on-premise instance is "not compatible" with cartodb.js 3.15. There's a disconnection between the version of CartoDB running on that instance and the version of cartodb.js :(. I can think of two possible solutions:

1. Update CartoDB in the instance so that the viz.json works with cartodb.js 3.15.
2. Point to cartodb.js 3.14 instead of 3.15.
