### ISSUE TITLE
Attributions added multiple times

### ISSUE THREAD

**Issue by haraldkj** [CartoDB/cartodb.js#695]
We are currently experiencing unwanted behaviour when adding attributionControl and a CartoDB-layer to the same map. We want to be able to add controls after layers, but it seems the new behaviour of attributions in Leaflet maps is in conflict with this. Is this intended?  

See this example: 

http://jsfiddle.net/afLgdkuj/3/

This is probably related to https://github.com/CartoDB/cartodb.js/commit/fcf3356540d1164eb1d1277cf9fa38c0708e0917.

**Comment by alonsogarciapablo** [comment]
Hello @haraldkj! Thanks for your example! I can see the `Statens kartverk` attribution is being displayed twice, but I'd say that has to do with the way Leaflet works. If you add another `L.control.attribution`, it will also have that attribution... What's the behaviour you would expect? Or what exactly are you trying to accomplish?

**Comment by haraldkj** [comment]
We currently have a map stack which incorporates several different providers. We would like to add one attribution control after all other layers have been added. We would also like to remove the default leaflet prefix as in the fiddle. 

An example is the map at http://www.nrk.no/norge/her-er-norges-nye-ordforere-1.12561458 which uses an older version of cartodb.js. The updated cartodb.js would result in an extra attributioncontrol on top of the map legend control.

Thanks.

**Comment by alonsogarciapablo** [comment]
Thanks again for the example. I think if you add more layers to the map, attributions should be displayed correctly. I don't see why you want/need to add another attributionControl after all layers have been added... could you please carify a bit more?

**Comment by alonsogarciapablo** [comment]
I might be wrong but, no matter when you add the `L.control.attribution`, it will display the attributions of all layers in the map. Take a look at this:

https://jsfiddle.net/afLgdkuj/5/

**Comment by haraldkj** [comment]
Yes, that makes sense. But it would be convenient to be able to decide when the control is to be added to the map, regardless of adding layers. 

We don't want multiple controllers - we would like all of our attributions in one attribution control. We basically do this:

http://jsfiddle.net/Lt17d3f4/1/

Currently, after the commit to cartodb.js mentioned above, cartodb.js will create and add a new attribution control to the map - even if the property is set to false in Leaflet.  

Maybe I'm wrong, but I think the more correct behaviour is to add attributions to the existing attribution control  - if any, and defer creating/adding of the attribution control to the encompassing application.

I can provide more examples if needed.

**Comment by alonsogarciapablo** [comment]
The thing is that we want to display the CartoDB attribution when a CartoDB layer is added to the map. That's the reason why need to add the attributionControl if the map doesn't have one.

Why wouldn't the following work?

http://jsfiddle.net/afLgdkuj/6/

**Comment by haraldkj** [comment]
I can see why you want the attribution to display regardless of Leaflet settings, but I still think it is somewhat counter-intuitive, since it overrides Leaflet behaviour.

We have developed an in-house map builder tool for journalists, built around Leaflet, CartoDB, Mapbox and several other services (modules are loaded on-demand). We try to avoid implementing custom logic when we can, and always add attributions to our maps (done as one of the last steps after all layers have been added). 

If this is the intended behavior of cartodb.js going forward, I guess we would have to add some checks to handle this case. Will you consider providing some other means of controlling cartoDB attributions? 

Thanks.

**Comment by acanimal** [comment]
Hi @haraldkj 
I spent some time trying to figure out how to make it work in the way you specify but I think it is not possible due the way Leaflet works.

Usually when you create a `L.map` an attribution control is created automatically and stored within the `map.attributionControl` variable. If you specify the `attributionControl: false` then the control is not created and the property `map.attributionControl` doesn't exists.

When you create a cartodb layer it tries to use the `map.attributionContol` if exists or creates a new one otherwise. In the last case, note the control is created but not stored withint the `map.attributionControl`.

Finally, if you add manually a new control like `map.addControl(L.control.attribution({'prefix': false}))` you have to attribution controls (without a reference to them), both showing the same attributions.

I propose you a different strategy that allows to decide you when to show the control:
- Create a map with default attribution control.
- Remove the control temporarily.
- Add as many layers you want.
- Add the control again.

See: http://jsfiddle.net/afLgdkuj/8

```javascript
    var map = L.map('map').setView([65, 18], 5);
    
    // Hide attribute control and modify prefix
    map.attributionControl.removeFrom(map);
    map.attributionControl.setPrefix('');
    
    // Add layers...
    ...
    
    // Show control again
    map.attributionControl.addTo(map);
```

This way only one attribution control is used and it shows all the layers attributions.

Cheers.
