### ISSUE TITLE
Format also small numbers of widgets

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb.js#851]
They are not formated when being > 1K for example

**Comment by xavijam** [comment]
Which widgets? Because:

<img width="372" alt="screen shot 2015-11-24 at 22 02 00" src="https://cloud.githubusercontent.com/assets/132146/11380546/116a00cc-92f7-11e5-8d9d-35d164c9f073.png">
<img width="367" alt="screen shot 2015-11-24 at 22 02 10" src="https://cloud.githubusercontent.com/assets/132146/11380547/116c082c-92f7-11e5-8397-5b54b25291b7.png">

**Comment by saleiva** [comment]
Histogram and categoría

S.

**Comment by xavijam** [comment]
For categories numbers are formatted too:
<img width="355" alt="screen shot 2015-11-25 at 09 30 20" src="https://cloud.githubusercontent.com/assets/132146/11392027/382e1544-9357-11e5-8525-d754d1dd34f3.png">
For histograms:
<img width="348" alt="screen shot 2015-11-25 at 09 30 36" src="https://cloud.githubusercontent.com/assets/132146/11392035/3fcf3206-9357-11e5-94fd-688d12defab4.png">

**Comment by saleiva** [comment]
Small numbers, those below the header

S.

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
For category :white_check_mark:  -> https://github.com/CartoDB/cartodb.js/commit/f1008374c1aebd258e7d8d6ab8191a83c8c40d13

@javierarce, your turn :).

**Comment by javierarce** [comment]
Histograms use formatted numbers too: 

![screen shot 2015-11-25 at 11 29 50](https://cloud.githubusercontent.com/assets/4933/11394792/8c4aef02-9367-11e5-831c-37c526df1149.png)
