### ISSUE TITLE
Fix broken examples

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb.js#938]
We have several broken examples (see easy.html, for instance).

**Comment by alonsogarciapablo** [comment]
I guess you're referring to the examples in the `v4` branch. If that's the case, they have been broken since we started the work on widgets (we changed the format of the viz.json). But also, since we extracted all the widgets related to widgets to the [deep-insights.js](https://github.com/CartoDB/deep-insights.js) repo, `CartoDB.js` is no longer working (the logic to create instances of layer groups in Windshaft and update the layer group model has been removed extracted and hence nobody is setting the tile URLs on the layer group model). I will open an issue explaining this and make sure I mention the examples.

cc: @viddo @rochoa

**Comment by viddo** [comment]
:+1:
